// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using full_stack_project_backend.Data;

#nullable disable

namespace full_stack_project_backend.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20261007193128_AddProgramsAndCareerPaths")]
    partial class AddProgramsAndCareerPaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("full_stack_project_backend.Models.CareerPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareerPaths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn to build fast, accessible interfaces with modern JavaScript frameworks.",
                            Name = "Frontend Developer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Design APIs, databases, and the systems that keep them running.",
                            Name = "Backend Developer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Turn raw numbers into decisions stakeholders can act on.",
                            Name = "Data Analyst"
                        });
                });

            modelBuilder.Entity("full_stack_project_backend.Models.CareerPathSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.ToTable("CareerPathSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerPathId = 1,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 2,
                            CareerPathId = 1,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 3,
                            CareerPathId = 1,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            CareerPathId = 1,
                            Name = "React"
                        },
                        new
                        {
                            Id = 5,
                            CareerPathId = 1,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 6,
                            CareerPathId = 2,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 7,
                            CareerPathId = 2,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 8,
                            CareerPathId = 2,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 9,
                            CareerPathId = 2,
                            Name = "REST APIs"
                        },
                        new
                        {
                            Id = 10,
                            CareerPathId = 2,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 11,
                            CareerPathId = 3,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 12,
                            CareerPathId = 3,
                            Name = "Excel"
                        },
                        new
                        {
                            Id = 13,
                            CareerPathId = 3,
                            Name = "Power BI"
                        },
                        new
                        {
                            Id = 14,
                            CareerPathId = 3,
                            Name = "Statistics"
                        });
                });

            modelBuilder.Entity("full_stack_project_backend.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("full_stack_project_backend.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerPathId = 1,
                            Description = "A project-based path from HTML basics to a production React app.",
                            Name = "Frontend Developer Program"
                        },
                        new
                        {
                            Id = 2,
                            CareerPathId = 2,
                            Description = "Build and ship a real API, from first endpoint to deployment.",
                            Name = "Backend Developer Program"
                        },
                        new
                        {
                            Id = 3,
                            CareerPathId = 3,
                            Description = "Go from spreadsheets to dashboards stakeholders actually use.",
                            Name = "Data Analyst Program"
                        });
                });

            modelBuilder.Entity("full_stack_project_backend.Models.CareerPathSkill", b =>
                {
                    b.HasOne("full_stack_project_backend.Models.CareerPath", "CareerPath")
                        .WithMany("Skills")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");
                });

            modelBuilder.Entity("full_stack_project_backend.Models.Program", b =>
                {
                    b.HasOne("full_stack_project_backend.Models.CareerPath", "CareerPath")
                        .WithMany("Programs")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareerPath");
                });

            modelBuilder.Entity("full_stack_project_backend.Models.CareerPath", b =>
                {
                    b.Navigation("Programs");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
